[book]
authors = ["Yuji Nagaoka"]
language = "ja"
multilingual = false
src = "src"
title = "Kotlin, Java データ構造について"
description = "workshop materials"

[preprocessor.katex]

[output.html]
additional-js = ["kotlin-pg.js"] # CDN 経由にしたい
